# Generated by Django 3.1.3 on 2020-11-21 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
            ],
            managers=[
                ('student', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ModelContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('payment', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('contractor', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ModelStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('fees', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('student', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ModelTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
                ('salary', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('teacher', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ModelCenterStudent',
            fields=[
                ('modelcenter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.modelcenter')),
                ('name', models.CharField(max_length=70)),
                ('roll', models.IntegerField()),
            ],
            bases=('payment.modelcenter',),
            managers=[
                ('student', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProxyModelStudent',
            fields=[
            ],
            options={
                'ordering': ['city'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.modelcenterstudent',),
            managers=[
                ('students', django.db.models.manager.Manager()),
            ],
        ),
    ]
