# Generated by Django 3.1.3 on 2020-11-22 05:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyModelStudent',
        ),
        migrations.CreateModel(
            name='ProxyModelCenterStudent',
            fields=[
            ],
            options={
                'ordering': ['city'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.modelcenterstudent',),
            managers=[
                ('student', django.db.models.manager.Manager()),
            ],
        ),
    ]
