# Generated by Django 3.1.3 on 2020-11-25 10:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20201122_1132'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='modelcenter',
            managers=[
                ('modelmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='modelcenterstudent',
            managers=[
                ('modelmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='modelcontractor',
            managers=[
                ('modelmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='modelstudent',
            managers=[
                ('modelmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='modelteacher',
            managers=[
                ('modelmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
