# Generated by Django 3.1.3 on 2020-11-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20201121_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelpost',
            old_name='user',
            new_name='createdby',
        ),
    ]
